name: Hair Band
time: 2015-06-18T16:50:47.4852158-05:00
pages: []
posts: []
related_posts: []
static_files: []
data: []
documents: []
categories: {}
tags: {}
root_path: C:\Users\itlackey\Source\Repos\HairBand\src\HairBand\wwwroot
install_completed: true
admin_enabled: true
more_info: info for the site
theme: Happy
